#!/usr/bin/env python3
"""
Register a new pharmacy client in the cloud database.

Run this on YOUR machine (not the client's) before each installation:

    cd backend
    DATABASE_URL="postgresql://..." python scripts/provision_client.py

The script creates an Organization, Branch, and Device row in Supabase,
generates a per-device sync token, and prints the .env block to paste
into setup-env.bat on the client machine.
"""
from __future__ import annotations

import hashlib
import os
import re
import secrets
import sys
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.db.base import SessionLocal
from app.models.tenancy import Branch, Device, DeviceStatus, Organization


def _prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    return value or default


def _slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:30]


def main() -> int:
    print("=== Pharma POS — Client Provisioning ===\n")
    print("This script creates cloud records for a new pharmacy installation.")
    print("Run it on YOUR machine. Paste the output into setup-env.bat.\n")

    org_name = _prompt("Pharmacy / organization name")
    if not org_name:
        print("Organization name is required.")
        return 1

    branch_name = _prompt("Branch name", default="Main Branch")
    branch_code = _prompt("Branch code (short slug)", default=_slugify(branch_name))
    branch_address = _prompt("Branch address (optional)")
    branch_phone = _prompt("Branch phone (optional)")
    device_name = _prompt("Device name", default="Main Till")

    db = SessionLocal()
    try:
        existing_org = db.query(Organization).filter(Organization.name == org_name).first()
        if existing_org:
            print(f"\nOrganization '{org_name}' already exists (id={existing_org.id}).")
            reuse = input("Reuse it and add a new branch/device? [y/N]: ").strip().lower()
            if reuse != "y":
                print("Aborted.")
                return 1
            org = existing_org
        else:
            org = Organization(name=org_name, is_active=True)
            db.add(org)
            db.flush()

        existing_branch = (
            db.query(Branch)
            .filter(Branch.organization_id == org.id, Branch.code == branch_code)
            .first()
        )
        if existing_branch:
            print(f"\nBranch code '{branch_code}' already exists under this org (id={existing_branch.id}).")
            reuse_branch = input("Reuse it and add a new device? [y/N]: ").strip().lower()
            if reuse_branch != "y":
                print("Aborted.")
                return 1
            branch = existing_branch
        else:
            branch = Branch(
                organization_id=org.id,
                name=branch_name,
                code=branch_code,
                address=branch_address or None,
                phone=branch_phone or None,
                is_active=True,
            )
            db.add(branch)
            db.flush()

        raw_token = secrets.token_urlsafe(32)
        token_hash = hashlib.sha256(raw_token.encode()).hexdigest()
        device_uid = str(uuid.uuid4())
        deployment_uid = str(uuid.uuid4())

        device = Device(
            organization_id=org.id,
            branch_id=branch.id,
            device_uid=device_uid,
            deployment_uid=deployment_uid,
            name=device_name,
            token_hash=token_hash,
            status=DeviceStatus.ACTIVE,
        )
        db.add(device)
        db.commit()

        print("\n" + "=" * 60)
        print("PROVISIONING COMPLETE")
        print("=" * 60)
        print(f"  Organization : {org.name} (id={org.id})")
        print(f"  Organization UID: {org.organization_uid}")
        print(f"  Branch       : {branch.name} / {branch.code} (id={branch.id})")
        print(f"  Branch UID   : {branch.branch_uid}")
        print(f"  Deployment UID: {deployment_uid}")
        print(f"  Device       : {device.name} (uid={device_uid})")
        print("=" * 60)
        print("\nPaste these values into setup-env.bat when prompted,")
        print("or add them directly to the client's backend\\.env:\n")
        print("# --- Cloud Sync (generated by provision_client.py) ---")
        print("CLOUD_SYNC_ENABLED=true")
        print(f"CLOUD_SYNC_INGEST_URL=https://pharma-pos-ai.onrender.com/api/sync/ingest")
        print(f"CLOUD_SYNC_API_TOKEN={raw_token}")
        print(f"CLOUD_SYNC_DEPLOYMENT_UID={deployment_uid}")
        print(f"CLOUD_SYNC_DEVICE_UID={device_uid}")
        print(f"CLOUD_SYNC_ORGANIZATION_ID={org.id}")
        print(f"CLOUD_SYNC_BRANCH_ID={branch.id}")
        print(f"CLOUD_SYNC_ORGANIZATION_UID={org.organization_uid}")
        print(f"CLOUD_SYNC_BRANCH_UID={branch.branch_uid}")
        print("# -----------------------------------------------------\n")
        print("IMPORTANT: The token above is shown once. Store it securely.")
        print("If lost, you must provision a new device.\n")

    except Exception as exc:
        db.rollback()
        print(f"Error: {exc}")
        return 1
    finally:
        db.close()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
