"""Enhanced pharmaceutical features - dosage forms, MOMO payments, prescriptions

Revision ID: fb40d0b95eb6
Revises: 31625c441d9e
Create Date: 2025-11-26 22:47:26.478006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb40d0b95eb6'
down_revision: Union[str, None] = '31625c441d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_batches', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('product_batches', sa.Column('received_date', sa.Date(), nullable=True))
    op.add_column('product_batches', sa.Column('is_quarantined', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('product_batches', sa.Column('quarantine_reason', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('dosage_form', sa.Enum('TABLET', 'CAPSULE', 'SYRUP', 'INJECTION', 'SUSPENSION', 'CREAM', 'OINTMENT', 'DROPS', 'POWDER', 'INHALER', 'SUPPOSITORY', 'PATCH', 'OTHER', name='dosageform'), nullable=True, server_default='TABLET'))
    op.add_column('products', sa.Column('strength', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('prescription_status', sa.Enum('PRESCRIPTION_REQUIRED', 'PRESCRIPTION_OPTIONAL', 'OTC', name='prescriptionstatus'), nullable=True))
    op.add_column('products', sa.Column('active_ingredient', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('manufacturer', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('usage_instructions', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('side_effects', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('contraindications', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('storage_conditions', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('drug_license_number', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('is_narcotic', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('products', sa.Column('requires_id', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('products', sa.Column('wholesale_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('reorder_level', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('reorder_quantity', sa.Integer(), nullable=True))
    op.add_column('sale_items', sa.Column('product_name', sa.String(length=200), nullable=True))
    op.add_column('sale_items', sa.Column('dosage_form', sa.String(length=50), nullable=True))
    op.add_column('sale_items', sa.Column('strength', sa.String(length=50), nullable=True))
    op.add_column('sale_items', sa.Column('batch_number', sa.String(length=100), nullable=True))
    op.add_column('sale_items', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('sale_items', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('status', sa.Enum('COMPLETED', 'PENDING', 'CANCELLED', 'REFUNDED', name='salestatus'), nullable=True, server_default='COMPLETED'))
    op.add_column('sales', sa.Column('discount_percentage', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('momo_reference', sa.String(length=100), nullable=True))
    op.add_column('sales', sa.Column('momo_number', sa.String(length=20), nullable=True))
    op.add_column('sales', sa.Column('customer_id_number', sa.String(length=50), nullable=True))
    op.add_column('sales', sa.Column('customer_address', sa.Text(), nullable=True))
    op.add_column('sales', sa.Column('prescription_number', sa.String(length=100), nullable=True))
    op.add_column('sales', sa.Column('doctor_name', sa.String(length=100), nullable=True))
    op.add_column('sales', sa.Column('has_prescription', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('sales', sa.Column('insurance_company', sa.String(length=100), nullable=True))
    op.add_column('sales', sa.Column('insurance_claim_number', sa.String(length=100), nullable=True))
    op.add_column('sales', sa.Column('insurance_coverage', sa.Float(), nullable=True, server_default='0'))
    op.add_column('sales', sa.Column('is_printed', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('sales', sa.Column('print_count', sa.Integer(), nullable=True, server_default='0'))
    # SQLite doesn't support ALTER COLUMN, so we skip changing payment_method type
    # The column type will be updated automatically when we recreate tables
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'payment_method',
               existing_type=sa.Enum('CASH', 'MOMO', 'CARD', 'BANK_TRANSFER', 'CREDIT', name='paymentmethod'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('sales', 'print_count')
    op.drop_column('sales', 'is_printed')
    op.drop_column('sales', 'insurance_coverage')
    op.drop_column('sales', 'insurance_claim_number')
    op.drop_column('sales', 'insurance_company')
    op.drop_column('sales', 'has_prescription')
    op.drop_column('sales', 'doctor_name')
    op.drop_column('sales', 'prescription_number')
    op.drop_column('sales', 'customer_address')
    op.drop_column('sales', 'customer_id_number')
    op.drop_column('sales', 'momo_number')
    op.drop_column('sales', 'momo_reference')
    op.drop_column('sales', 'tax_rate')
    op.drop_column('sales', 'discount_percentage')
    op.drop_column('sales', 'status')
    op.drop_column('sale_items', 'tax_amount')
    op.drop_column('sale_items', 'expiry_date')
    op.drop_column('sale_items', 'batch_number')
    op.drop_column('sale_items', 'strength')
    op.drop_column('sale_items', 'dosage_form')
    op.drop_column('sale_items', 'product_name')
    op.drop_column('products', 'reorder_quantity')
    op.drop_column('products', 'reorder_level')
    op.drop_column('products', 'wholesale_price')
    op.drop_column('products', 'requires_id')
    op.drop_column('products', 'is_narcotic')
    op.drop_column('products', 'drug_license_number')
    op.drop_column('products', 'storage_conditions')
    op.drop_column('products', 'contraindications')
    op.drop_column('products', 'side_effects')
    op.drop_column('products', 'usage_instructions')
    op.drop_column('products', 'manufacturer')
    op.drop_column('products', 'active_ingredient')
    op.drop_column('products', 'prescription_status')
    op.drop_column('products', 'strength')
    op.drop_column('products', 'dosage_form')
    op.drop_column('product_batches', 'quarantine_reason')
    op.drop_column('product_batches', 'is_quarantined')
    op.drop_column('product_batches', 'received_date')
    op.drop_column('product_batches', 'location')
    # ### end Alembic commands ###
