"""
Vendor admin API — manage pharmacy clients (organizations, branches, devices).

All endpoints require the ADMIN role. These run on the cloud (Render) and are
accessed from the vendor dashboard at pharma-pos-ai.vercel.app. Client machines
never call these endpoints.
"""
from __future__ import annotations

import hashlib
import secrets
import uuid
from datetime import datetime, timezone
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.api.dependencies import require_admin
from app.core.config import settings
from app.db.base import get_db
from app.models.tenancy import Branch, Device, DeviceStatus, Organization
from app.models.user import User
from app.schemas.tenancy import (
    BranchCreate,
    BranchDetail,
    BranchUpdate,
    DeviceCreate,
    DeviceDetail,
    DeviceProvisionResponse,
    DeviceStatusUpdate,
    OrganizationCreate,
    OrganizationDetail,
    OrganizationUpdate,
)

router = APIRouter(prefix="/admin", tags=["Admin — Client Management"])


# ── Helpers ───────────────────────────────────────────────────────────────────

def _org_detail(db: Session, org: Organization) -> OrganizationDetail:
    branch_count = db.query(func.count(Branch.id)).filter(Branch.organization_id == org.id).scalar() or 0
    device_count = db.query(func.count(Device.id)).filter(Device.organization_id == org.id).scalar() or 0
    return OrganizationDetail(
        id=org.id,
        name=org.name,
        legal_name=org.legal_name,
        contact_phone=org.contact_phone,
        contact_email=org.contact_email,
        is_active=org.is_active,
        created_at=org.created_at,
        branch_count=branch_count,
        device_count=device_count,
    )


def _branch_detail(db: Session, branch: Branch) -> BranchDetail:
    device_count = db.query(func.count(Device.id)).filter(Device.branch_id == branch.id).scalar() or 0
    return BranchDetail(
        id=branch.id,
        organization_id=branch.organization_id,
        name=branch.name,
        code=branch.code,
        phone=branch.phone,
        address=branch.address,
        is_active=branch.is_active,
        created_at=branch.created_at,
        device_count=device_count,
    )


def _device_detail(device: Device) -> DeviceDetail:
    return DeviceDetail(
        id=device.id,
        organization_id=device.organization_id,
        branch_id=device.branch_id,
        device_uid=device.device_uid,
        name=device.name,
        status=device.status,
        last_seen_at=device.last_seen_at,
        created_at=device.created_at,
        organization_name=device.organization.name if device.organization else None,
        branch_name=device.branch.name if device.branch else None,
    )


def _env_block(device: Device, raw_token: str) -> str:
    ingest_url = (
        settings.CLOUD_SYNC_INGEST_URL
        or "https://pharma-pos-ai.onrender.com/api/sync/ingest"
    )
    return (
        "# --- Cloud Sync (generated by vendor dashboard) ---\n"
        "CLOUD_SYNC_ENABLED=true\n"
        f"CLOUD_SYNC_INGEST_URL={ingest_url}\n"
        f"CLOUD_SYNC_API_TOKEN={raw_token}\n"
        f"CLOUD_SYNC_DEVICE_UID={device.device_uid}\n"
        f"CLOUD_SYNC_ORGANIZATION_ID={device.organization_id}\n"
        f"CLOUD_SYNC_BRANCH_ID={device.branch_id}\n"
        "# ---------------------------------------------------\n"
        "# IMPORTANT: This token is shown once. Store it securely.\n"
        "# If lost, rotate the token from the vendor dashboard."
    )


# ── Organizations ─────────────────────────────────────────────────────────────

@router.get("/organizations", response_model=List[OrganizationDetail])
def list_organizations(
    active_only: bool = Query(False),
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    q = db.query(Organization)
    if active_only:
        q = q.filter(Organization.is_active.is_(True))
    orgs = q.order_by(Organization.name).all()
    return [_org_detail(db, o) for o in orgs]


@router.post("/organizations", response_model=OrganizationDetail, status_code=status.HTTP_201_CREATED)
def create_organization(
    data: OrganizationCreate,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    if db.query(Organization).filter(Organization.name == data.name).first():
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Organization name already exists")
    org = Organization(
        name=data.name,
        legal_name=data.legal_name,
        contact_phone=data.contact_phone,
        contact_email=str(data.contact_email) if data.contact_email else None,
        is_active=True,
    )
    db.add(org)
    db.commit()
    db.refresh(org)
    return _org_detail(db, org)


@router.patch("/organizations/{org_id}", response_model=OrganizationDetail)
def update_organization(
    org_id: int,
    data: OrganizationUpdate,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    org = db.query(Organization).filter(Organization.id == org_id).first()
    if not org:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Organization not found")
    if data.name is not None:
        existing = db.query(Organization).filter(Organization.name == data.name, Organization.id != org_id).first()
        if existing:
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Organization name already exists")
        org.name = data.name
    if data.legal_name is not None:
        org.legal_name = data.legal_name
    if data.contact_phone is not None:
        org.contact_phone = data.contact_phone
    if data.contact_email is not None:
        org.contact_email = str(data.contact_email)
    if data.is_active is not None:
        org.is_active = data.is_active
    db.commit()
    db.refresh(org)
    return _org_detail(db, org)


# ── Branches ──────────────────────────────────────────────────────────────────

@router.get("/organizations/{org_id}/branches", response_model=List[BranchDetail])
def list_branches(
    org_id: int,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    org = db.query(Organization).filter(Organization.id == org_id).first()
    if not org:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Organization not found")
    branches = db.query(Branch).filter(Branch.organization_id == org_id).order_by(Branch.name).all()
    return [_branch_detail(db, b) for b in branches]


@router.post("/organizations/{org_id}/branches", response_model=BranchDetail, status_code=status.HTTP_201_CREATED)
def create_branch(
    org_id: int,
    data: BranchCreate,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    org = db.query(Organization).filter(Organization.id == org_id).first()
    if not org:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Organization not found")
    if db.query(Branch).filter(Branch.organization_id == org_id, Branch.code == data.code).first():
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=f"Branch code '{data.code}' already exists in this organization")
    branch = Branch(
        organization_id=org_id,
        name=data.name,
        code=data.code,
        phone=data.phone,
        address=data.address,
        is_active=True,
    )
    db.add(branch)
    db.commit()
    db.refresh(branch)
    return _branch_detail(db, branch)


@router.patch("/organizations/{org_id}/branches/{branch_id}", response_model=BranchDetail)
def update_branch(
    org_id: int,
    branch_id: int,
    data: BranchUpdate,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    branch = db.query(Branch).filter(Branch.id == branch_id, Branch.organization_id == org_id).first()
    if not branch:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Branch not found")
    if data.name is not None:
        branch.name = data.name
    if data.phone is not None:
        branch.phone = data.phone
    if data.address is not None:
        branch.address = data.address
    if data.is_active is not None:
        branch.is_active = data.is_active
    db.commit()
    db.refresh(branch)
    return _branch_detail(db, branch)


# ── Devices ───────────────────────────────────────────────────────────────────

@router.get("/devices", response_model=List[DeviceDetail])
def list_all_devices(
    org_id: Optional[int] = Query(None),
    status_filter: Optional[DeviceStatus] = Query(None, alias="status"),
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    q = db.query(Device)
    if org_id:
        q = q.filter(Device.organization_id == org_id)
    if status_filter:
        q = q.filter(Device.status == status_filter)
    devices = q.order_by(Device.organization_id, Device.branch_id, Device.name).all()
    return [_device_detail(d) for d in devices]


@router.post(
    "/organizations/{org_id}/branches/{branch_id}/devices",
    response_model=DeviceProvisionResponse,
    status_code=status.HTTP_201_CREATED,
)
def provision_device(
    org_id: int,
    branch_id: int,
    data: DeviceCreate,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    """
    Create a new device and return its raw sync token once.
    The token is never stored — if lost, use rotate-token to generate a new one.
    """
    org = db.query(Organization).filter(Organization.id == org_id).first()
    if not org:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Organization not found")
    branch = db.query(Branch).filter(Branch.id == branch_id, Branch.organization_id == org_id).first()
    if not branch:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Branch not found")

    raw_token = secrets.token_urlsafe(32)
    token_hash = hashlib.sha256(raw_token.encode()).hexdigest()
    device_uid = str(uuid.uuid4())

    device = Device(
        organization_id=org_id,
        branch_id=branch_id,
        device_uid=device_uid,
        name=data.name,
        token_hash=token_hash,
        status=DeviceStatus.ACTIVE,
    )
    db.add(device)
    db.commit()
    db.refresh(device)

    return DeviceProvisionResponse(
        id=device.id,
        organization_id=device.organization_id,
        branch_id=device.branch_id,
        device_uid=device.device_uid,
        name=device.name,
        status=device.status,
        created_at=device.created_at,
        raw_token=raw_token,
        env_block=_env_block(device, raw_token),
    )


@router.patch("/devices/{device_id}/status", response_model=DeviceDetail)
def update_device_status(
    device_id: int,
    data: DeviceStatusUpdate,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    device = db.query(Device).filter(Device.id == device_id).first()
    if not device:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Device not found")
    device.status = data.status
    db.commit()
    db.refresh(device)
    return _device_detail(device)


@router.post("/devices/{device_id}/rotate-token", response_model=DeviceProvisionResponse)
def rotate_device_token(
    device_id: int,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    """
    Generate a new token for a device, invalidating the old one immediately.
    The raw token is returned once — update the client machine's backend/.env.
    """
    device = db.query(Device).filter(Device.id == device_id).first()
    if not device:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Device not found")

    raw_token = secrets.token_urlsafe(32)
    device.token_hash = hashlib.sha256(raw_token.encode()).hexdigest()
    device.updated_at = datetime.now(timezone.utc)
    db.commit()
    db.refresh(device)

    return DeviceProvisionResponse(
        id=device.id,
        organization_id=device.organization_id,
        branch_id=device.branch_id,
        device_uid=device.device_uid,
        name=device.name,
        status=device.status,
        created_at=device.created_at,
        raw_token=raw_token,
        env_block=_env_block(device, raw_token),
    )
